[build-system]
requires = ["setuptools>=67"]
build-backend = "setuptools.build_meta"

[project]
name = "alpha-factory-v1"
version = "1.0.0"
description = "Alpha-Factory v1"
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
alpha-factory = "alpha_factory_v1.run:run"
governance-sim = "alpha_factory_v1.demos.solving_agi_governance.governance_sim:main"

[project.entry-points."alpha_factory.agents"]
# custom agents can be registered here
