apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alpha-factory-remote.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "alpha-factory-remote.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "alpha-factory-remote.name" . }}
    spec:
      volumes:                      # ① shared emptyDir for SPIFFE UDS
        - name: spire-socket
          emptyDir: {}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
          {{- end }}
          args: ["/app/entrypoint.sh", "--worker-only"]   # see note below
          ports:
            - containerPort: 8000   # A2A RPC
            - containerPort: 3000   # UI (optional)
          resources: {{- toYaml .Values.resources | nindent 12 }}

{{ include "af.spiffeSidecar" . | indent 8 }}   # ② inject side‑car when enabled
