apiVersion: v1
kind: Service
metadata:
  name: {{ include "alpha-factory-remote.fullname" . }}
  labels:
    app.kubernetes.io/name: alpha-factory
spec:
  type: {{ .Values.workerService.type }}
  ports:
    - port: {{ .Values.workerService.port }}
      targetPort: 8000
      protocol: TCP
      name: rpc
    - port: {{ .Values.env.METRICS_PORT | default 9090 }}
      targetPort: {{ .Values.env.METRICS_PORT | default 9090 }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "alpha-factory-remote.name" . }}
