apiVersion: v1
kind: Service
metadata:
  name: {{ include "alpha-asi-demo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "alpha-asi-demo.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 7860
