version: "3.9"

services:
  alpha-factory:
    # Re‑use the *existing* service definition from docker-compose.yml
    # and only override the bits below.
    volumes:
      - ./backend:/app/backend:rw,consistent
      - ./ui:/ui:rw,consistent
    environment:
      - ALPHA_MARKET_PROVIDER=SIM
    command: >
      sh -c "
        npm --prefix /ui install &&
        npm --prefix /ui run dev -- --host &
        exec /app/entrypoint.sh
      "
    ports:
      - "5173:5173"  # Vite dev server
      - "8000:8000"  # FastAPI
