apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alpha-demo
  template:
    metadata:
      labels:
        app: alpha-demo
    spec:
      containers:
        - name: orchestrator
          image: {{ .Values.image }}
          env:
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
            - name: RUN_MODE
              value: {{ .Values.env.RUN_MODE | quote }}
          ports:
            - containerPort: 8000
            - containerPort: 3000
