apiVersion: v1
kind: Service
metadata:
  name: alpha-demo
spec:
  type: ClusterIP
  selector:
    app: alpha-demo
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: ui
      port: 3000
      targetPort: 3000
