apiVersion: v1
kind: Service
metadata:
  name: alpha-demo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: alpha-demo
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: 8501
    - name: bus
      port: {{ .Values.service.busPort }}
      targetPort: 6006
