apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-insight
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alpha-insight
  template:
    metadata:
      labels:
        app: alpha-insight
    spec:
      containers:
        - name: orchestrator
          image: {{ .Values.image }}
          env:
            - name: OPENAI_API_KEY
              value: {{ .Values.env.OPENAI_API_KEY | quote }}
            - name: RUN_MODE
              value: {{ .Values.env.RUN_MODE | quote }}
            - name: AGI_INSIGHT_OFFLINE
              value: {{ .Values.env.AGI_INSIGHT_OFFLINE | quote }}
            - name: AGI_INSIGHT_BUS_PORT
              value: {{ .Values.env.AGI_INSIGHT_BUS_PORT | quote }}
            - name: AGI_INSIGHT_LEDGER_PATH
              value: {{ .Values.env.AGI_INSIGHT_LEDGER_PATH | quote }}
          ports:
            - containerPort: 8000
            - containerPort: 8501
            - containerPort: 6006
