# SPDX-License-Identifier: Apache-2.0
name: Ensure Repository Owner
description: Fail if the workflow is triggered by someone other than the repository owner.
outputs:
  repo_owner_lower:
    description: Lowercase repository owner
    value: ${{ steps.set-owner.outputs.repo_owner_lower }}
runs:
  using: composite
  steps:
    - name: Check owner
      shell: bash
      run: |
        actor="${{ github.actor }}"
        repo_owner="${{ github.repository_owner }}"

        if [ "$actor" = "github-actions[bot]" ]; then
          echo "workflow-dispatch initiated by GitHub Actions bot; allowing run."
          exit 0
        fi

        if [ "$actor" != "$repo_owner" ]; then
          echo "Only the repository owner or an in-repo automation run can trigger this workflow."
          echo "actor=$actor repo_owner=$repo_owner"
          exit 1
        fi
    - name: Set owner output
      id: set-owner
      shell: bash
      run: |
        repo_owner_lower="${GITHUB_REPOSITORY_OWNER,,}"
        echo "repo_owner_lower=$repo_owner_lower" >> "$GITHUB_OUTPUT"
