# SPDX-License-Identifier: Apache-2.0
name: Ensure Repository Owner
description: Fail if the workflow is triggered by someone other than the repository owner.
runs:
  using: composite
  steps:
    - name: Check owner
      shell: bash
      run: |
        if [ "${{ github.actor }}" != "${{ github.repository_owner }}" ]; then
          echo "Only the repository owner can run this workflow."
          exit 1
        fi
