# SPDX-License-Identifier: Apache-2.0
name: Setup Insight Assets
description: Cache, fetch and verify Insight Browser assets.
runs:
  using: composite
  steps:
    - name: Configure asset cache directory
      shell: bash
      run: |
        echo "FETCH_ASSETS_DIR=${RUNNER_TEMP}/insight-assets" >> "$GITHUB_ENV"
        echo "INSIGHT_ASSET_ROOT=${RUNNER_TEMP}/insight-assets" >> "$GITHUB_ENV"
    - name: Generate asset key
      id: asset-key
      uses: ./.github/actions/generate-asset-key
    - name: Cache Pyodide and GPT-2 assets
      id: asset-cache
      uses: actions/cache@v5.0.2 # 8b402f58fbc84540c8b491a91e594a4576fec3d7
      with:
        path: ${{ env.FETCH_ASSETS_DIR }}
        key: assets-${{ steps.asset-key.outputs.key }}-${{ runner.os }}
        restore-keys: assets-${{ runner.os }}-
    - name: Fetch Insight Browser assets
      shell: bash
      env:
        FETCH_ASSETS_DIR: ${{ env.FETCH_ASSETS_DIR }}
      run: python scripts/fetch_assets.py
    - name: Verify Insight Browser assets
      shell: bash
      run: |
        set -eo pipefail
        FETCH_ASSETS_DIR="${FETCH_ASSETS_DIR}" python scripts/fetch_assets.py --verify-only 2>&1 | tee verify.log
        if [ "${PIPESTATUS[0]}" -ne 0 ]; then
          echo "::error::Insight asset verification failed. Check FETCH_ASSETS_DIR cache." >&2
          cat verify.log
          exit 1
        fi
