# Default configuration for the α‑AGI Insight demo
episodes: 5
exploration: 1.4
rewriter: random
target: 3
seed: 0
model: gpt-4o
# comma-separated list or YAML array of sectors
# sectors: [Finance, Healthcare, Education]
