# SPDX-License-Identifier: Apache-2.0
name: Setup CI Environment
description: Build sandbox image, install Playwright browsers and show tool versions.
outputs:
  sandbox-image:
    description: Normalized sandbox image tag used for sandbox builds.
    value: ${{ steps.resolve-sandbox.outputs.resolved }}
runs:
  using: composite
  steps:
    - name: Resolve sandbox image tag
      id: resolve-sandbox
      shell: bash
      run: |
        set -euo pipefail

        default_tag="selfheal-sandbox:latest"
        raw_value="${SANDBOX_IMAGE:-$default_tag}"

        # Strip whitespace and accidental wrapping quotes to avoid passing an empty
        # or invalid tag to Docker when the env var is defined as "" or contains
        # only spaces.
        sanitized="${raw_value//[[:space:]]/}"
        sanitized="${sanitized//\"/}"
        sanitized="${sanitized//\'/}"

        # Fall back to the known-good default if the sanitized value disappears.
        if [[ -z "$sanitized" ]]; then
          sanitized="$default_tag"
        fi

        if [[ -z "$sanitized" ]]; then
          echo "::error::SANDBOX_IMAGE is empty. Provide a tag or rely on the default selfheal-sandbox:latest."
          exit 1
        fi

        echo "SANDBOX_IMAGE=$sanitized" >> "$GITHUB_ENV"
        echo "resolved=$sanitized" >> "$GITHUB_OUTPUT"
        echo "Using sandbox image tag: $sanitized"

    - name: Build sandbox image
      shell: bash
      env:
        RESOLVED_SANDBOX_IMAGE: ${{ steps.resolve-sandbox.outputs.resolved }}
      run: |
        set -euo pipefail

        default_tag="selfheal-sandbox:latest"
        tag="${RESOLVED_SANDBOX_IMAGE:-${SANDBOX_IMAGE:-$default_tag}}"
        tag="${tag//[[:space:]]/}"
        tag="${tag//\"/}"
        tag="${tag//\'/}"

        # Fallback defensively if an upstream env override stripped the tag
        # unexpectedly (e.g., SANDBOX_IMAGE=""), ensuring Docker never sees an
        # empty repository name.
        if [[ -z "${tag}" ]]; then
          echo "::warning::SANDBOX_IMAGE resolved to an empty value; falling back to ${default_tag}."
          tag="$default_tag"
        fi

        docker build -t "${tag}" -f sandbox.Dockerfile .
    - name: Show tool versions
      shell: bash
      run: |
        python --version
        node --version
        docker --version
        docker compose version
        git --version
    - name: Install Playwright browsers
      shell: bash
      run: python -m playwright install chromium webkit firefox || echo "SKIP_WEBKIT_TESTS=1" >> "$GITHUB_ENV"
