# SPDX-License-Identifier: Apache-2.0
name: Setup CI Environment
description: Build sandbox image, install Playwright browsers and show tool versions.
outputs:
  sandbox-image:
    description: Normalized sandbox image tag used for sandbox builds.
    value: ${{ steps.resolve-sandbox.outputs.resolved }}
runs:
  using: composite
  steps:
    - name: Resolve sandbox image tag
      id: resolve-sandbox
      shell: bash
      run: |
        # Normalize and validate the sandbox tag so docker always receives a non-empty value.
        resolved="${SANDBOX_IMAGE:-selfheal-sandbox:latest}"
        # Strip whitespace and accidental wrapping quotes to avoid passing an
        # empty or invalid tag to Docker when the env var is defined as "".
        resolved="${resolved//[[:space:]]/}"
        resolved="${resolved//\"/}"
        resolved="${resolved//\'/}"

        if [[ -z "$resolved" ]]; then
          resolved="selfheal-sandbox:latest"
        fi

        if [[ -z "$resolved" ]]; then
          echo "::error::SANDBOX_IMAGE is empty. Provide a tag or rely on the default selfheal-sandbox:latest."
          exit 1
        fi

        echo "SANDBOX_IMAGE=$resolved" >> "$GITHUB_ENV"
        echo "resolved=$resolved" >> "$GITHUB_OUTPUT"
        echo "Using sandbox image tag: $resolved"

    - name: Build sandbox image
      shell: bash
      env:
        RESOLVED_SANDBOX_IMAGE: ${{ steps.resolve-sandbox.outputs.resolved }}
      run: |
        tag="${RESOLVED_SANDBOX_IMAGE:-${SANDBOX_IMAGE:-selfheal-sandbox:latest}}"
        tag="${tag//[[:space:]]/}"
        tag="${tag//\"/}"
        tag="${tag//\'/}"

        if [[ -z "${tag}" ]]; then
          echo "::error::Resolved SANDBOX_IMAGE is empty; aborting sandbox build."
          exit 1
        fi

        docker build -t "${tag}" -f sandbox.Dockerfile .
    - name: Show tool versions
      shell: bash
      run: |
        python --version
        node --version
        docker --version
        docker compose version
        git --version
    - name: Install Playwright browsers
      shell: bash
      run: python -m playwright install chromium webkit firefox || echo "SKIP_WEBKIT_TESTS=1" >> "$GITHUB_ENV"
