# SPDX-License-Identifier: Apache-2.0
"""Build the Insight Discovery Workbench from preserved source templates."""
from __future__ import annotations

import json
from pathlib import Path
import re
import runpy

ROOT = Path(__file__).resolve().parents[1]


def build(root: Path = ROOT) -> None:
    templates = root / "scripts/templates"
    demo = root / "alpha_factory_v1/demos/alpha_agi_insight_v0"
    version = json.loads((root / "alpha_factory_v1/demos/catalog.json").read_text())["release"]
    destination = root / "docs/alpha_agi_insight_v0"
    destination.mkdir(parents=True, exist_ok=True)
    (destination / "index.html").write_text(
        (templates / "discovery.html").read_text().replace("{{VERSION}}", version), encoding="utf-8"
    )
    (destination / "research.html").write_bytes((templates / "discovery-original.html").read_bytes())
    assets = root / "docs/assets/discovery"
    assets.mkdir(parents=True, exist_ok=True)
    (assets / "scenarios.json").write_bytes((demo / "scenarios.json").read_bytes())
    for name in ("engine.mjs", "workbench.mjs"):
        module = assets / name
        if module.is_file():
            module.write_text(re.sub(r"\?v=\d+\.\d+\.\d+", "?v=" + version, module.read_text()))
    model = runpy.run_path(str(demo / "discovery.py"))
    case = json.loads((demo / "scenarios.json").read_text())[0]
    report = model["evaluate"](case)
    import html

    rows = []
    for index, row in enumerate(report["result"]["ranking"][:4]):
        y = 155 + index * 38
        low = row["scores"]["low"] / 1_000_000
        high = row["scores"]["high"] / 1_000_000
        rows.append(
            f'<text x="30" y="{y}" font-size="12" fill="#253e35">{html.escape(row["sector"])}</text>'
            f'<path d="M{270 + low * 2.5:.2f} {y - 4} H{270 + high * 2.5:.2f}" '
            'stroke="#b9c78e" stroke-width="6"/>'
            f'<circle cx="{270 + low * 2.5:.2f}" cy="{y - 4}" r="4" fill="#174f42"/>'
        )
    (assets / "preview.svg").write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="360" viewBox="0 0 600 360" '
        'role="img" aria-labelledby="title"><title id="title">Insight Discovery: synthetic review priorities</title>'
        '<rect width="600" height="360" fill="#f6f4ed"/>'
        '<g font-family="Arial,sans-serif"><text x="30" y="38" font-size="11" fill="#526460" '
        'letter-spacing="2">01 / INSIGHT DISCOVERY</text>'
        '<text x="30" y="92" font-family="Georgia,serif" font-size="34" fill="#192d2b">Find the opening.</text>'
        '<path d="M30 116 H570" stroke="#ccd2c7"/>'
        + "".join(rows)
        + '<text x="30" y="330" font-size="10" fill="#526460">SYNTHETIC INPUTS · INDEPENDENT REVIEW REQUIRED</text>'
        '<text x="545" y="333" font-family="Georgia,serif" font-size="30" fill="#174f42">α</text></g></svg>\n'
    )
    (assets / "constants.mjs").write_text(
        "// SPDX-License-Identifier: Apache-2.0\n"
        "// Generated by scripts/generate_discovery.py.\n"
        "// prettier-ignore\nexport default " + json.dumps({"scope": model["SCOPE"]}, separators=(",", ":")) + ";\n"
    )


if __name__ == "__main__":
    build()
