# SPDX-License-Identifier: Apache-2.0
"""Build the governance workbench and preserve its original research presentation."""
from __future__ import annotations

import json
from pathlib import Path
import runpy
import re

ROOT = Path(__file__).resolve().parents[1]


def build(root: Path = ROOT) -> None:
    templates = root / "scripts/templates"
    demo = root / "alpha_factory_v1/demos/solving_agi_governance"
    version = json.loads((root / "alpha_factory_v1/demos/catalog.json").read_text())["release"]
    page = (templates / "governance.html").read_text()
    (root / "docs/solving_agi_governance/index.html").write_text(
        page.replace("{{VERSION}}", version).replace(
            "{{LEGACY}}", (templates / "governance-legacy.html").read_text().strip()
        )
    )
    assets = root / "docs/assets/governance"
    assets.mkdir(parents=True, exist_ok=True)
    (assets / "scenarios.json").write_bytes((demo / "scenarios.json").read_bytes())
    for name in ("engine.mjs", "workbench.mjs"):
        module = assets / name
        if module.is_file():
            module.write_text(re.sub(r"\?v=\d+\.\d+\.\d+", "?v=" + version, module.read_text()))
    model = runpy.run_path(str(demo / "workbench.py"))
    data = {"bounds": model["BOUNDS"], "gates": model["GATES"], "scope": model["SCOPE"]}
    (assets / "constants.mjs").write_text(
        "// SPDX-License-Identifier: Apache-2.0\n"
        "// Generated by scripts/generate_governance.py; do not edit by hand.\n"
        "// prettier-ignore\nexport default " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )


if __name__ == "__main__":
    build()
