# SPDX-License-Identifier: Apache-2.0
"""Generate canonical and packaged Experience Lab assets, retaining original research."""
from __future__ import annotations

import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from alpha_factory_v1.demos.era_of_experience.lab import SCOPE


def build(root: Path = ROOT) -> None:
    demo = root / "alpha_factory_v1/demos/era_of_experience"
    docs = root / "docs"
    templates = root / "scripts/templates"
    version = json.loads((root / "alpha_factory_v1/demos/catalog.json").read_text())["release"]
    page = (templates / "experience.html").read_text().replace("{{VERSION}}", version)
    (docs / "era_of_experience/index.html").write_text(page, encoding="utf-8")
    (docs / "era_of_experience/research.html").write_bytes((templates / "experience-original.html").read_bytes())
    assets = docs / "assets/experience"
    assets.mkdir(parents=True, exist_ok=True)
    (assets / "scenarios.json").write_bytes((demo / "scenarios.json").read_bytes())
    (assets / "constants.mjs").write_text(
        "// SPDX-License-Identifier: Apache-2.0\n// Generated by scripts/generate_experience.py.\n"
        "// prettier-ignore\nexport default " + json.dumps({"scope": SCOPE}, separators=(",", ":")) + ";\n"
    )
    for module in assets.glob("*.mjs"):
        module.write_text(re.sub(r"\?v=\d+\.\d+\.\d+", "?v=" + version, module.read_text()), encoding="utf-8")
    (assets / "preview.svg").write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="360" viewBox="0 0 600 360" '
        'role="img" aria-labelledby="title">'
        '<title id="title">Experience Lab: act, observe, learn, challenge</title>'
        '<rect width="600" height="360" fill="#173b36"/>'
        '<g font-family="Arial,sans-serif"><text x="32" y="38" fill="#d9eea6" font-size="11" letter-spacing="2">'
        "ERA OF EXPERIENCE / LEARNING LAB</text>"
        '<g font-family="Georgia,serif" fill="#f5f3ed" font-size="40"><text x="32" y="101">Experience changes</text>'
        '<text x="32" y="147" fill="#d9eea6" font-style="italic">the next decision.</text></g>'
        '<path d="M32 187 H568" stroke="#688777"/>'
        '<g fill="#d9eea6" font-size="12"><text x="32" y="232">01 / ACT</text><text x="165" y="232">02 / OBSERVE</text>'
        '<text x="315" y="232">03 / LEARN</text><text x="445" y="232">04 / TEST</text></g>'
        '<path d="M32 262 H568" stroke="#688777"/>'
        '<text x="32" y="323" font-size="11" fill="#d1dfd5">SYNTHETIC OUTCOMES · INDEPENDENT REVIEW</text>'
        '<text x="537" y="328" font-family="Georgia,serif" font-size="35" fill="#d9eea6">α</text></g></svg>\n'
    )
    # The wheel serves only this small allowlist; no source tree or credentials are exposed.
    (docs / "era_of_experience/assets/lab-preview.svg").write_bytes((assets / "preview.svg").read_bytes())
    web = demo / "web"
    target = web / "era_of_experience/index.html"
    target.parent.mkdir(parents=True, exist_ok=True)
    packaged = page.replace('<html lang="en">', '<html lang="en" data-packaged="true">')
    public = "https://montrealai.github.io/AGI-Alpha-Agent-v0/"
    for old, new in {
        'href="../"': f'href="{public}"',
        'href="../index.html"': f'href="{public}"',
        'href="../demos/era_of_experience/"': f'href="{public}demos/era_of_experience/"',
        'href="../ascension-protocol/"': f'href="{public}ascension-protocol/"',
        'href="../DISCLAIMER_SNIPPET/"': f'href="{public}DISCLAIMER_SNIPPET/"',
        'href="research.html"': f'href="{public}era_of_experience/research.html"',
    }.items():
        packaged = packaged.replace(old, new)
    target.write_text(packaged, encoding="utf-8")
    names = [str(path.relative_to(docs)) for path in assets.iterdir() if path.is_file()]
    names += [
        "assets/discovery/engine.mjs",
        "assets/discovery/constants.mjs",
        "assets/compounding/engine.mjs",
        "assets/ascension/crypto.mjs",
    ]
    for name in names:
        destination = web / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        data = (docs / name).read_text(encoding="utf-8")
        if name.endswith(".mjs"):
            data = re.sub(r"\?v=\d+\.\d+\.\d+", "?v=" + version, data)
        destination.write_text(data, encoding="utf-8")


if __name__ == "__main__":
    build()
