version: '3.9'
services:
  orchestrator:
    build: .
    image: alpha-demo:latest
    env_file:
      - ../.env
    environment:
      RUN_MODE: api
    ports:
      - "${PORT:-8000}:8000"

  agents:
    image: alpha-demo:latest
    env_file:
      - ../.env
    environment:
      RUN_MODE: cli
    depends_on:
      - orchestrator

  web:
    image: alpha-demo:latest
    env_file:
      - ../.env
    environment:
      RUN_MODE: web
    ports:
      - "3000:3000"
    depends_on:
      - orchestrator
