apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alpha-factory.fullname" . }}
  labels:
    {{- include "alpha-factory.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "alpha-factory.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "alpha-factory.name" . }}
    spec:
      volumes:
        - name: spire-socket
          emptyDir: {}
      containers:
        - name: orchestrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $k, $v := .Values.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
          {{- end }}
          args: ["/app/entrypoint.sh"]
          ports:
            - containerPort: {{ .Values.service.port }}   # REST + gRPC
            - containerPort: {{ .Values.service.uiPort }}  # UI
            - containerPort: {{ .Values.env.METRICS_PORT | default 9090 }}  # metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: {{- toYaml .Values.resources | nindent 12 }}
{{ include "af.spiffeSidecar" . | indent 8 }}
