{{- /*
helm/alpha-factory/templates/secret.yaml
────────────────────────────────────────────────────────────────────────────
Kubernetes Secret that injects all runtime credentials into the α‑Factory
pods.  Inspired by agentic‑trading’s pattern but extended for every key
referenced in `.env.sample`.

Usage
─────
Values are populated from `values.yaml → env`.  If users prefer to supply an
existing Secret (e.g., via Vault / ExternalSecrets), set:

  existingSecret: "my-precreated-secret"

and this template will be skipped.

*/ -}}
{{- if not .Values.existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alpha-factory.fullname" . }}-secrets
  labels:
    {{- include "alpha-factory.labels" . | nindent 4 }}
type: Opaque
stringData:
  # ─── Core LLM credentials ────────────────────────────────────────────
  OPENAI_API_KEY:  {{ .Values.env.OPENAI_API_KEY  | default "" | quote }}
  GOOGLE_API_KEY:  {{ .Values.env.GOOGLE_API_KEY  | default "" | quote }}

  # ─── Market data & broker creds ──────────────────────────────────────
  POLYGON_API_KEY:     {{ .Values.env.POLYGON_API_KEY     | default "" | quote }}
  ALPACA_KEY_ID:       {{ .Values.env.ALPACA_KEY_ID       | default "" | quote }}
  ALPACA_SECRET_KEY:   {{ .Values.env.ALPACA_SECRET_KEY   | default "" | quote }}
  IBKR_CLIENT_ID:      {{ .Values.env.IBKR_CLIENT_ID      | default "" | quote }}
  IBKR_CLIENT_SECRET:  {{ .Values.env.IBKR_CLIENT_SECRET  | default "" | quote }}

  # ─── Governance & telemetry keys ─────────────────────────────────────
  VC_SIGNING_KEY: |
{{- if .Values.env.VC_SIGNING_KEY }}
    {{- .Values.env.VC_SIGNING_KEY | nindent 4 }}
{{- else }}
    # paste PEM‑encoded ed25519 private key here if not using an ExternalSecret
{{- end }}

  # ─── Misc / overrides (non‑sensitive but convenient) ─────────────────
  LLM_PROVIDER: {{ .Values.env.LLM_PROVIDER | default "openai" | quote }}

{{- end }}
