apiVersion: v1
kind: Service
metadata:
  name: {{ include "alpha-factory.fullname" . }}
  labels:
    {{- include "alpha-factory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
      protocol: TCP
      name: ui
  selector:
    app: {{ include "alpha-factory.name" . }}
