version: '3.9'

services:
  omni-demo:
    build: .
    image: omni-factory:latest
    container_name: omni-demo
    environment:
      # Provide API key only if you want LLM-powered scenario variety
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Persist CityCoin ledger between runs
      - ./omni_ledger.sqlite:/app/omni_ledger.sqlite
    restart: unless-stopped
    networks:
      - omni-net

  # Optional – lightweight monitoring stack
  prometheus:
    image: prom/prometheus:latest
    container_name: omni-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - omni-net

  grafana:
    image: grafana/grafana:latest
    container_name: omni-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - omni-net

networks:
  omni-net:
    driver: bridge
