name: "📈 Replay Bench"

on:
  workflow_dispatch:

jobs:
  replay-bench:
    if: github.event_name == 'workflow_dispatch' && github.actor == github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
          pip install -r requirements-dev.txt
      - name: Run replay harness
        run: python scripts/run_replay_bench.py
      - name: Run micro benchmarks
        run: |
          make benchmark
      - name: Upload micro benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: micro-bench-results
          path: bench_results.json
      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/bench_history.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update bench history"
            git push
          fi
