name: "🚀 Deploy — Kind"

on:
  workflow_dispatch:
    inputs:
      run_token:
        description: 'Authorization token for maintainers'
        required: false

permissions:
  contents: read

jobs:
  deploy-kind:
    runs-on: ubuntu-latest
    steps:
      - name: Check dispatch token
        if: github.actor != github.repository_owner
        run: |
          if [ "${{ github.event.inputs.run_token }}" != "${{ secrets.DISPATCH_TOKEN }}" ]; then
            echo "Unauthorized"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Set up Kind cluster
        uses: helm/kind-action@v1.7.0

      - name: Build Insight demo image
        run: |
          docker build -t insight-demo:local infrastructure

      - name: Load image into Kind
        run: kind load docker-image insight-demo:local

      - name: Deploy Helm chart
        run: |
          helm install insight infrastructure/helm-chart --values infrastructure/helm-chart/values.yaml

      - name: Apply Terraform
        working-directory: infrastructure/terraform
        run: |
          terraform init -backend=false
          terraform apply -auto-approve

      - name: Wait for service readiness
        run: |
          kubectl wait --for=condition=Ready pods --all --timeout=120s
          kubectl get pods
