name: "📊 Transfer Matrix"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      run_expensive_tests:
        description: "Run costly tests"
        required: false
        default: "no"

jobs:
  transfer-matrix:
    if: github.event_name == 'workflow_dispatch' && github.actor == 'MontrealAI' && github.event.inputs.run_expensive_tests == 'yes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
          pip install -r requirements-dev.txt
      - name: Run transfer test
        run: |
          python -m alpha_factory_v1.demos.alpha_agi_insight_v1.src.interface.cli transfer-test --models "o3-mini,llama-3" --top-n 5
      - name: Upload matrix
        uses: actions/upload-artifact@v4
        with:
          name: transfer-matrix
          path: results/transfer_matrix.csv
