name: "🔒 Container Security"

on:
  workflow_dispatch:
    inputs:
      run_token:
        description: 'Authorization token for maintainers'
        required: false

env:
  DOCKER_IMAGE: alpha-factory
  DOCKERHUB_REPO: montrealai/alpha-factory

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  sbom-scan-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Check dispatch token
        if: github.actor != github.repository_owner
        run: |
          if [ "${{ github.event.inputs.run_token }}" != "${{ secrets.DISPATCH_TOKEN }}" ]; then
            echo "Unauthorized"
            exit 1
          fi
      - uses: actions/checkout@v4 # 11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-python@v5 # a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'requirements.lock'

      - name: Compute repo_owner_lower
        run: echo "repo_owner_lower=$(echo \"${{ github.repository_owner }}\" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Cache pre-commit
        uses: actions/cache@v4.2.3 # 5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: .cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-precommit-
      - uses: actions/setup-node@v4 # 49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: '.nvmrc'

      - name: Install SBOM tools
        run: |
          python -m pip install --upgrade pip cyclonedx-bom
          npm install -g @cyclonedx/bom
      - name: Install pre-commit
        run: pip install pre-commit==4.2.0
        env:
          PRE_COMMIT_HOME: .cache/pre-commit
      - name: Run pre-commit checks
        run: |
          from_ref="${{ github.event.before }}"
          if [ -n "$from_ref" ]; then
            pre-commit run --from-ref "$from_ref" --to-ref "${{ github.sha }}"
          else
            pre-commit run --all-files
          fi
        env:
          PRE_COMMIT_HOME: .cache/pre-commit

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }} -f Dockerfile .

      - name: Generate Python SBOM
        run: cyclonedx-py -r requirements.lock -o sbom-python.json

      - name: Generate Node SBOM
        run: cyclonedx-bom -o sbom-node.json src/interface/web_client

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.0.10 # bceef37a45815d6c5cfea1861a414ec7dbc00242
        with:
          image-ref: ghcr.io/${{ env.repo_owner_lower }}/$DOCKER_IMAGE:${{ github.sha }}
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH

      - name: Login to GHCR
        uses: docker/login-action@v3.4.0 # 74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }}

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.9.2 # d58896d6a1865668819e1d91763c7751a165e159
        with:
          cosign-release: 'v2.2.4'

      - name: Sign container
        run: cosign sign --yes ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }}

      - name: Verify signature
        run: cosign verify ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }}

      - name: Generate provenance
        run: |
          cosign generate --type slsaprovenance ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }} > provenance.json
          cosign attest --yes --predicate provenance.json --type slsaprovenance ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0 # 74a5d142397b4f367a81961eba4e8cd7edddf772
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker tag ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }} "$DOCKERHUB_REPO:${{ github.ref_name }}"
          docker tag ghcr.io/$repo_owner_lower/$DOCKER_IMAGE:${{ github.sha }} "$DOCKERHUB_REPO:latest"
          docker push "$DOCKERHUB_REPO:${{ github.ref_name }}"
          docker push "$DOCKERHUB_REPO:latest"

      - name: Upload artifacts to release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2.3.2 # 72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          files: |
            sbom-python.json
            sbom-node.json
            provenance.json
